# Generated by Django 5.1.4 on 2025-01-16 13:35

import django.core.files.storage
import django.utils.timezone
import ruchky_backend.helpers.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="age",
        ),
        migrations.AddField(
            model_name="pet",
            name="birth_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Birth Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pet",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=ruchky_backend.helpers.db.models.generate_filename,
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="sex",
            field=models.CharField(
                choices=[("f", "Female"), ("m", "Male")],
                default="f",
                max_length=1,
                verbose_name="Sex",
            ),
            preserve_default=False,
        ),
    ]
