# Generated by Django 5.1.6 on 2025-03-04 16:03

import django.core.files.storage
import django.db.models.deletion
import ruchky_backend.helpers.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_pet_short_description_petsociallink_uuidtaggeditem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to=ruchky_backend.helpers.db.models.generate_filename,
                        verbose_name="Image",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which the image appears in the gallery",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Caption"
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="pets.pet",
                        verbose_name="Pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet Image",
                "verbose_name_plural": "Pet Images",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="pet",
            name="profile_picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_for",
                to="pets.petimage",
                verbose_name="Profile Picture",
            ),
        ),
    ]
