# Generated by Django 5.2 on 2025-05-06 10:05

import django.core.files.storage
import ruchky_backend.helpers.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0005_breed_alter_pet_breed"),
    ]

    operations = [
        migrations.AddField(
            model_name="breed",
            name="image_hover",
            field=models.ImageField(
                blank=True,
                help_text="Image displayed on hover",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=ruchky_backend.helpers.db.models.generate_filename,
                verbose_name="Breed Image Hover",
            ),
        ),
    ]
