# Generated by Django 5.2 on 2025-05-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0006_breed_image_hover"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="is_hypoallergenic",
            field=models.BooleanField(default=False, verbose_name="Hypoallergenic"),
        ),
    ]
